Feature/create login
yuta10200831/7-2.docker-templete pull request #12
Opened 2023-09-02 10:11 UTC by yuta10200831

2023-09-04 03:15 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-09-04 03:15 UTC, KatsuyaTanaka95 commented on src/public/login.php
> +<a href="register.php">アカウントを作る</a>
「要件定義書をもとにBlogアプリを作成しましょう。」という課題なので、ファイル名等も要件定義書と同じものにしましょう！

2023-09-05 01:15 UTC, yuta10200831 commented on src/public/login.php
> +<a href="register.php">アカウントを作る</a>
修正しました

2023-09-05 01:15 UTC, yuta10200831 commented
要件定義書を参考にし、ファイル名の修正をしました。
ご確認宜しくお願い致します！

2023-09-06 03:49 UTC, KatsuyaTanaka95 requested changes
「アカウント作成ボタンの押下時、user/signup_complete.phpに画面遷移。」とあるので、
そのような仕様にしましょう！
そして、ユーザー登録の機能は、user/signup_complete.phpでを実行しましょう！
ユーザー登録の機能とは、画像の①〜③の箇所です！

「アカウント作成ボタンの押下時、user/signup_complete.phpに画面遷移。」と書いてあることに疑問がでなかったでしょうか？？
user/signup_complete.phpという単語が出ているので無視をしないでください！

疑問点や不明点があれば、確認しましょう！

<img width="1440" alt="スクリーンショット 2023-09-06 12 48 26" src="https://github.com/yuta10200831/7-2.docker-templete/assets/63081802/df76582c-edf3-4614-ba63-1de24b698d8e">

2023-09-06 08:06 UTC, yuta10200831 commented
申し訳ありません。。自己解決してしまっておりました。
改めて修正しましたのでご確認宜しくお願いします。

2023-09-07 05:30 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-09-07 05:30 UTC, KatsuyaTanaka95 commented on src/public/user/signin_complete.php
> +}
ここをガード節で書きましょ〜〜

2023-09-07 05:30 UTC, KatsuyaTanaka95 commented on src/public/user/signup_complete.php
> +    }
ここもガード節で書きましょ〜〜

2023-09-07 07:22 UTC, yuta10200831 commented
修正しました。
ご確認宜しくお願いいたします！

2023-09-08 07:12 UTC, merged