feat:新規登録機能実装、ログイン機能修正、ログアウト機能実装
yuta10200831/7-2.docker-templete pull request #13
Opened 2023-09-02 14:26 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/2-Blog-6aa81fd6027645849442a405dc1c27ad

## 作業詳細
・新規登録機能を実装
　バリデーションに問題がなかったらDBへ保存
　正しくなかったらエラーメッセージを表示
・ログイン機能の修正
　ログイン時、入力が正しくなかったらエラーメッセージを表示
・ログアウト機能の実装

2023-09-04 03:19 UTC, KatsuyaTanaka95 requested changes
ログアウト機能実装 はいい感じだと思います！！

新規登録機能、ログイン機能に関しては、要件定義書の仕様にしましょう！（ファイル名等）

2023-09-05 04:50 UTC, yuta10200831 commented
要件定義書通りにファイル名を修正しました。

2023-09-06 08:38 UTC, yuta10200831 commented
修正しました！
ご確認宜しくお願いします。

2023-09-07 05:34 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-09-07 05:34 UTC, KatsuyaTanaka95 commented on src/public/user/signin.php
> +    }
ここをガード節で書きましょ〜〜

2023-09-07 05:34 UTC, KatsuyaTanaka95 commented on src/public/user/signin.php
> +if ($_SERVER['REQUEST_METHOD'] === 'POST') {
ここは、要件定義書にはないので、削除しちゃいましょう！！

2023-09-07 05:34 UTC, KatsuyaTanaka95 commented on src/public/user/signup.php
> +if ($_SERVER['REQUEST_METHOD'] === 'POST') {
ここは、要件定義書にはないので、削除しちゃいましょう！！

2023-09-07 05:34 UTC, KatsuyaTanaka95 commented on src/public/user/signup.php
> +    }
ここをガード節で書きましょ〜〜

2023-09-08 00:26 UTC, KatsuyaTanaka95 approved these changes
こちらもLGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-09-08 07:15 UTC, merged