feat:新規登録機能の実装
yuta10200831/7-2.docker-templete pull request #14
Opened 2023-09-03 09:43 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/2-Blog-6aa81fd6027645849442a405dc1c27ad

## 作業詳細
新規投稿の実装
ユーザーログインしている状態の時のみ、新規投稿が出来る

2023-09-04 03:24 UTC, KatsuyaTanaka95 requested changes
要件定義書の通りの仕様にしましょう！

2023-09-05 06:16 UTC, yuta10200831 commented
修正しました！
・ファイル名の修正
<img width="1594" alt="スクリーンショット 2023-09-05 15 12 00" src="https://github.com/yuta10200831/7-2.docker-templete/assets/124555669/c80b09e7-8002-4e38-b239-e833d8dfe367">

※新規記事登録フォームを表示。
新規作成ボタン押下時にpost/store.phpに遷移。

2023-09-06 04:10 UTC, KatsuyaTanaka95 requested changes
ファイル名の変更ありがとうございます！！

以下の質問の回答をさせていただきます！
現場では、基本的に要件定義書の通りに作成すると思いますので、その練習をした方がよいとおもいます！
また、やったことのないものであれば、体験しておいたほうが良いかとおもいます！

「新規作成ボタン押下時にpost/store.phpに遷移。」の箇所ですが、、
新規作成ボタンをクリックしたときに、post/store.phpファイルが表示されるようにするということです！（これを確認するためのテスト観点でもあります。テスト観点を書いた際に疑問点や不明点の確認ができるとタイミング的にはいいと思います！）

要件定義書にあるように、post/store.phpファイルで新規投稿機能のコードを書きましょう！
<img width="1439" alt="スクリーンショット 2023-09-06 13 05 20" src="https://github.com/yuta10200831/7-2.docker-templete/assets/63081802/1c3ae5fe-25c5-45ef-94f2-cb38096a7eb5">


> ※新規記事登録フォームを表示。
> 新規作成ボタン押下時にpost/store.phpに遷移。
> →こちらの意味がよくわからないです。
> 　ページを作る必要があるのでしょうか？
> 　新規投稿ボタンを押下後にindex.phpに遷移し、後の機能追加で一覧機能を表示させておりますがそれではだめでしょうか。
> 
> ご確認宜しくお願い致します。

2023-09-06 12:25 UTC, yuta10200831 commented
修正しました！
ご確認、質問に対する回答ありがとうございます。
改めてご確認宜しくお願い致します。

2023-09-07 08:14 UTC, yuta10200831 commented
修正しました！
こちらにてご確認宜しくお願い致します。

2023-09-08 00:30 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-09-08 00:30 UTC, KatsuyaTanaka95 commented on src/public/create.php
> +}
ここが必要なさそうです！！

2023-09-08 00:30 UTC, KatsuyaTanaka95 commented on src/public/post/store.php
> +}
ここも必要なさそうです！

2023-09-08 07:24 UTC, yuta10200831 commented
修正しました！
ご確認宜しくお願い致します。

2023-09-10 21:35 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-09-11 05:24 UTC, merged