feat:マイページの実装
yuta10200831/7-2.docker-templete pull request #16
Opened 2023-09-03 12:58 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/2-Blog-6aa81fd6027645849442a405dc1c27ad

## 作業詳細
マイページの実装
・自分の投稿した投稿のみ表示
・記事詳細へのボタン表示
・新規投稿ボタンの表示

2023-09-04 03:35 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-09-04 03:35 UTC, KatsuyaTanaka95 commented on src/public/mypage.php
> +}
ユーザー認証機能を要件定義書の通りの仕様にしましょう！

2023-09-05 05:58 UTC, yuta10200831 commented on src/public/mypage.php
> +}
修正済み

2023-09-05 05:59 UTC, yuta10200831 commented
・ユーザー認証気を変更
・ファイル名の変更

2023-09-06 03:56 UTC, KatsuyaTanaka95 approved these changes
マイページの実装はいい感じだと思います！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-09-11 05:29 UTC, merged