feat:記事詳細機能、コメント機能の実装
yuta10200831/7-2.docker-templete pull request #17
Opened 2023-09-03 14:42 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/2-Blog-6aa81fd6027645849442a405dc1c27ad

## 作業詳細
・topページからの記事詳細機能を実装
・記事に対してのコメント機能を実装
・コメント機能にエラーメッセージが出す

## 気になる点・不安な点

2023-09-04 03:50 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-09-04 03:50 UTC, KatsuyaTanaka95 commented on src/public/detail.php
> +        </section>
<img width="1440" alt="スクリーンショット 2023-09-04 12 41 59" src="https://github.com/yuta10200831/7-2.docker-templete/assets/63081802/a4f6fe20-6135-42e4-950a-d89ab7dc68ef">

「記事へのコメント機能」は、「comment/store.php」で作成するという仕様になっているので、そのように変更しましょう！！
要件定義書の見方は、「1. お問合せフォームを作成してみよう」でやっているかと思いますので、そちらを再度みてください！！
https://www.notion.so/1-21ca6947b0e9459381c7de1f948b8981?pvs=4#4fa11bcceab043218546419eaa751aeb

2023-09-05 06:42 UTC, yuta10200831 commented on src/public/detail.php
> +        </section>
・ファイル名の修正をしました
・「記事へのコメント機能」は、「comment/store.php」で作成するという仕様
→コメント機能を新しくファイルを作って実装するという意味ですか？
　現状detail.phpで実装しています。

2023-09-06 04:37 UTC, KatsuyaTanaka95 requested changes
ファイル名のご修正ありがとうございます！

以下の質問の回答です！
この質問では、正直、正しく認識を合わせることができません！
そして、毎回僕が布石木さんがわからないであろうことを予測して０から説明するとなると、0から教えるのと変わらないことになってしまいます！（この研修の目的とは違うものになります！）
この研修は、誰にでもわかりやすく手取り足取りなんでも教える研修ではございません！
エンジニアとして、現場に入ったときに自力で業務をやりきる力をつけるための研修です！
何度も伝えているとは思いますが、確認と質問の仕方も工夫していきましょう！（ここはできる前提の研修となっています！）

アプリ作成をする課題の一番初めにトライした「お問い合わせフォームの作成」の課題とほとんど同じです！（index.phpとcomplete.php）
お問い合わせフォームのコードの理解ができていれば、できるはずです！

> 「記事へのコメント機能」は、「comment/store.php」で作成するという仕様
> →コメント機能を新しくファイルを作って実装するという意味ですか？
> 　現状detail.phpで実装しています。

2023-09-06 13:40 UTC, yuta10200831 commented
修正しました。
ご確認宜しくお願い致します！

質問に具体性がなかったです、申し訳ありませんでした。
誰が見ても分かる質問の仕方を心がけます。

確認と仕方に関しては私自身今後も考えながら学習していきます。
考えてないわけではないので、今後も試行錯誤していきたいと思います。
人よりもできていない分人一倍努力をしていくので引き続き宜しくお願い致します！

2023-09-07 06:38 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-09-07 06:38 UTC, KatsuyaTanaka95 commented on src/public/detail.php
> +}
ここもUserIdでのチェックにしましょう！

2023-09-08 00:33 UTC, KatsuyaTanaka95 approved these changes
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-09-11 05:32 UTC, merged