feat:Create機能をDDD構造にする
yuta10200831/7-2.docker-templete pull request #26
Opened 2023-09-30 07:11 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/2-1758b8c7441944bc8206cebc259a7459

## 作業詳細
Create機能をDDD構造にする

※QueryServiseのファイルを作らないで完成させております。
もし、QueryServiseファイルの作成も必要でしたらご連絡頂きたいです。
今の形からQueryServiseを作成する方法がわからないのでその際は質問させて下さい。

2023-10-01 18:29 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-10-01 18:29 UTC, KatsuyaTanaka95 commented on src/public/create.php
> +        }
create.phpに保存処理は必要そうでしょうか？？
保存処理をするのは、store.phpだったと思います！！

2023-10-01 18:29 UTC, KatsuyaTanaka95 commented on src/public/post/store.php
> +$createPostInteractor = new CreatePostInteractor($postRepository);
ログイン機能と同じような構成で作りましょう！！！
UseCaseInputは、UseCaseInteractorの引数に渡しましょう！！

2023-10-04 00:07 UTC, yuta10200831 commented on src/public/create.php
> +        }
修正済み

2023-10-04 00:37 UTC, yuta10200831 commented on src/public/post/store.php
> +$createPostInteractor = new CreatePostInteractor($postRepository);
修正済み

2023-10-04 04:10 UTC, yuta10200831 commented
修正致しました！
ご確認宜しくお願い致します。

2023-10-06 04:43 UTC, KatsuyaTanaka95 commented on src/public/post/store.php
> +$createPostInteractor = new CreatePostInteractor($postRepository);
ログイン機能と同じような構成になっていませんね！！！
「ログイン機能と同じような構成」とは、どういうことだと捉えましたでしょうか？
違った意味で捉えていたのであればいいですが、、
もし、どういうことかわからないけど、確認しなかったのであれば、よくないです！！！！

2023-10-06 04:47 UTC, KatsuyaTanaka95 commented on src/public/create.php
> +        }
> create.phpに保存処理は必要そうでしょうか？？

こちらに関しての回答はいかがでしょうか？？
何度かこのような質問を無視していますが、なぜでしょうか？？

2023-10-06 04:56 UTC, KatsuyaTanaka95 commented on src/public/post/store.php
> +$createPostInteractor = new CreatePostInteractor($postRepository);
`$postRepository = new PostRepositoryMySQLImpl($pdo);`
上記のコードは使用する直前で書きましょう！

何度か言ってますので、次同じようなミスがないように工夫しましょう！
↑↑このように言われた場合は、次からOOして同じミスがないようにします！と返信するようにしましょう！

ふせきさんの場合は、「工夫しましょう」と呼びかけても、直るまでにかなり時間がかかるので、どのような工夫をするか相手に言う癖をつけた方がよいと思います！
そうすることで、「どのような工夫をするか」をより明確に考えるきっかけができると思いますので、、、、

<img width="862" alt="スクリーンショット 2023-10-06 13 40 01" src="https://github.com/yuta10200831/7-2.docker-templete/assets/63081802/a54661d1-59b2-4284-85f6-690a9a8fae9b">

2023-10-06 05:13 UTC, KatsuyaTanaka95 commented on src/public/post/store.php
> +$createPostInteractor = new CreatePostInteractor($postRepository);
ログイン機能は以下のスクショのように構成されています。store.phpも同じような構成にしましょう。

①使用したいファイルを読み込んでいる。
②post（またはget）送信で値を受け取っている。
③tryの中で、post（またはget）送信で受け取った
値のチェックをしている。
④ValueObjectをnewしている。
（※ store.phpでは、ValueObjectを使用しなくても良いですが、練習として作成しましょう。）
⑤UseCaseを使用し、メインの処理をしている。
（①UseCaseInputをnewする。②UseCaseInteractorをnewする。このとき、UseCaseInputを引数に渡す。③UseCaseInteractorのhandlerメソッドを呼び出し、UseCaseOutputを受け取る。）
⑥UseCaseOutputの値によって適切な処理をする。
⑦エラーが起きたときの処理をcatchに書く

<img width="657" alt="スクリーンショット 2023-10-06 13 56 30" src="https://github.com/yuta10200831/7-2.docker-templete/assets/63081802/823274fd-959d-4428-a624-03e2aa8a9605">

2023-10-07 14:30 UTC, yuta10200831 commented on src/public/create.php
> +        }
大変申し訳ありませんでした。
言葉のニュアンス的な所で、質問として認識しておりませんでした。
全く無視していたわけではありませんが、私が書き込んだ文面だと無視していると捉えられてしまっても仕方がないと思います。自己完結した上で修正してしまっておりました。
対面ではない以上、相手の事を考えてコメントするべきだと思います。


ちなみにですが、こちらのコメントを見てあ、store.phpで保存処理しているからあえてcreate.phpに書く必要ないなと思いました。

2023-10-07 14:34 UTC, yuta10200831 commented on src/public/post/store.php
> +$createPostInteractor = new CreatePostInteractor($postRepository);
ログイン機能と同じような構成になっていませんね！！！
「ログイン機能と同じような構成」とは、どういうことだと捉えましたでしょうか？
違った意味で捉えていたのであればいいですが、、
もし、どういうことかわからないけど、確認しなかったのであれば、よくないです！！！！

→こちら間違えた捉え方をしておりました。
　私の中で処理を分割可するという認識で作業を進めてしまっておりました。
　

2023-10-07 14:48 UTC, yuta10200831 commented on src/public/post/store.php
> +$createPostInteractor = new CreatePostInteractor($postRepository);
$postRepository = new PostRepositoryMySQLImpl($pdo);
上記のコードは使用する直前で書きましょう！

何度か言ってますので、次同じようなミスがないように工夫しましょう！
↑↑このように言われた場合は、次からOOして同じミスがないようにします！と返信するようにしましょう！

ふせきさんの場合は、「工夫しましょう」と呼びかけても、直るまでにかなり時間がかかるので、どのような工夫をするか相手に言う癖をつけた方がよいと思います！
そうすることで、「どのような工夫をするか」をより明確に考えるきっかけができると思いますので、、、、


→同じ様なミスが多いのは自負しております。。
　付箋に書いて見える所に貼ってみたりしているのですが、根本を変える必要があると感じております。
　言われた事はメモしていつでも見れるようにしていたりもします。。

(今後工夫すること)
◯最終的な確認不足による所が多いと思いますので作業の仕方根本を変えます。
　→PCを操作する際にあまりマウスを使っておりませんでした。
　　実装完了した時に確認して、よし！やっとできたーとなりキーボードでポンポンとプッシュしていました。
　　今後、プッシュ、コミットをする際は確認した後に再度立ち止まりマウスを使ってゆっくりと作業していきます。
◯コードの量、ファイルの数が増えてきているのでロジックを紙に書き出します
◯こうした方がいい、と言われた所に関してはグーグルキープで私はいつもメモを取っているので書き込みリマインダーで定期的に確認出来る様にします

2023-10-08 01:43 UTC, yuta10200831 commented
改めて修正いたしました。
頂いた画像、コメントと見比べながらコード修正していきましたがこんな感じでしょうか、、
ご確認宜しくお願いします！

2023-10-10 02:54 UTC, KatsuyaTanaka95 commented on src/public/create.php
> +        }
そういうことでしたか！！！！！
ご回答ありがとうございます！！

次回からコードを整理してから提出をお願いします！！
僕から見ると、コードを理解せずにコピペで作ってとりあえず動いたから提出したようにも見えます！！もしそうなっていたら良くないのでやめましょう！

また、コードが「ぐちゃぐちゃ」OR「汚くて読みずらい」とエンジニアとしてはやっていけないです！！！ここは、頑張ってください！！！

2023-10-10 03:07 UTC, KatsuyaTanaka95 commented on src/public/post/store.php
> +$createPostInteractor = new CreatePostInteractor($postRepository);
ありがとうございます！！！
工夫はいいものが多いですね！！
すでにやられているものも素晴らしいです！！

しかし、「最終的な確認不足による所が多い」というのをより解消できるものを考えた方がいいと思います！
「最終的な確認不足」の原因は、「できたという気持ちで勢いで提出する」以外にも、「最終的に何を確認するべきか忘れている」というのもあるとは思います！
なので、毎回確実にチェックするにはどうするかも考えてください！！！

2023-10-10 03:48 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-10-10 03:48 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseInput/CreatePostInputData.php
> +}
SignUpInput.phpと全然違う構造になってます！！！
他のファイルも違う構造になっているところがあるので、修正しましょう！！

なぜ、違う構造になってしまっていますでしょうか？？
原因を教えてください！！！！ご確認をお願いします！！

2023-10-14 10:58 UTC, yuta10200831 commented on src/public/post/store.php
> +$createPostInteractor = new CreatePostInteractor($postRepository);
なるほど、確かにそうですね！
この前田中さんにお伺いした事早速実践し始めています。
その中の作業手順メモに沿って一つ一つ確認していきたいと思います。
一旦このやり方で進めていきたいと思っています！

2023-10-14 11:04 UTC, yuta10200831 commented on src/public/create.php
> +        }
承知いたしました！
コードを整理して提出出来るようにします。

2023-10-15 07:20 UTC, yuta10200831 commented on src/app/UseCase/UseCaseInput/CreatePostInputData.php
> +}
承知致しました！
ゲッターメソッド
getTitle(): タイトルのValue Objectを返す。
getContents(): 内容のValue Objectを返す。
getUserId(): ユーザーIDを返す。
上記三点を修正する事でSignupと同じ動きになるようにしています。

下記のスクショはSignUpInteractor.phpの抜粋です。
こちらでNewUserをnewしていますがcreate機能ではNewCreateを作っておりません
この方が見やすいと思って意図的にこの様な設計にしていますが、ここも合わせたほうがいいのでしょうか。。
![スクリーンショット 2023-10-15 16 16 52](https://github.com/yuta10200831/7-2.docker-templete/assets/124555669/8911d1bf-3932-4f7b-a4a6-b057965217aa)

ご確認宜しくお願いします！

2023-10-15 07:22 UTC, yuta10200831 commented
お疲れ様です！
改めて修正致しました。
下記大まかな修正点です。

## 修正点
・CreatePostInput.phpを修正しました。
・下記スクショのstore.phpでの登録処理のロジックを修正しました。
　 Usecaseを使って登録処理ができる様、全体的に修正しました。
![スクリーンショット 2023-10-15 16 02 48](https://github.com/yuta10200831/7-2.docker-templete/assets/124555669/b2a25d84-4c20-4d96-8ced-8be2f2e4407f)
・Signupと相違のあるファイル名を修正

以上です

ご確認宜しくお願いします！

2023-10-16 04:24 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-10-16 04:24 UTC, KatsuyaTanaka95 commented on src/app/Domain/ValueObject/Post/Title.php
> +        }
ここは文字の数の制限にしておきましょう！！
（例えば、30文字以内とか。。。。）

2023-10-16 04:24 UTC, KatsuyaTanaka95 commented on src/app/Domain/ValueObject/Post/Contents.php
> +        $this->value = $value;
ここは文字の数の制限にしておきましょう！！
（例えば、3000文字以内とか。。。。）

2023-10-16 04:24 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseInteractor/CreatePostInteractor.php
> +    }
見本では、Daoはnewしていなかったと思います！！ここでnewした意図を教えてほしいです！！！！（どのように学習を進めているか確認したいので、聞いてみました！）
<img width="1436" alt="スクリーンショット 2023-10-16 13 16 00" src="https://github.com/yuta10200831/7-2.docker-templete/assets/63081802/75b8478c-1b1b-42d9-a7db-aebbf0d3e1a2">

2023-10-16 04:24 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseOutput/CreatePostOutput.php
> +    }
見本では、idを返していなかったと思います！！

2023-10-16 04:27 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseInput/CreatePostInputData.php
> +}
Postエンティティを作成してるみたいですね！！いいと思います！！！

2023-10-16 23:45 UTC, yuta10200831 commented on src/app/Domain/ValueObject/Post/Title.php
> +        }
承知致しました！
毎回設定ですね、メモっておきます！

2023-10-16 23:52 UTC, yuta10200831 commented on src/app/Domain/ValueObject/Post/Contents.php
> +        $this->value = $value;
承知致しました！
修正致します！

2023-10-17 00:30 UTC, yuta10200831 commented on src/app/UseCase/UseCaseInteractor/CreatePostInteractor.php
> +    }
見本ではRepotitoryでnewしているのはわかっていてこの様にしていました。。
あ、こういうやり方もあるのだなと思いInteractorでnewしていました、、
コメントなどに残して置けばよかったです、申し訳ありません。
Repotitoryファイルでnewする様に作り直しましたのでご確認宜しくお願い致します。

2023-10-17 23:54 UTC, yuta10200831 commented
お疲れ様です！
改めて修正致しました。
ご確認宜しくお願いします！

2023-10-18 21:35 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-10-18 21:35 UTC, KatsuyaTanaka95 commented on src/public/post/store.php
> +} catch (\Exception $e) {
ユーザー登録機能のように処理が成功したか確認をするコード等もかきましょう！！

- ユーザー登録機能は、「userテーブルにデータを保存する機能」
- ブログの登録機能は、「blogテーブルにデータを保存する機能」
なので、、保存するテーブルが違うだけで、ほとんど同じ感じでかけばいいんだなってなるとよいです！！
（もし、もともとなっていたのであれば、次回以降どうすればやり直しが減るか考えて、実践してみてください！）

<img width="804" alt="スクリーンショット 2023-10-19 6 28 51" src="https://github.com/yuta10200831/7-2.docker-templete/assets/63081802/e2d79c7a-afd3-4e6c-b9a3-932cb0565073">

2023-10-19 10:09 UTC, yuta10200831 commented on src/public/post/store.php
> +} catch (\Exception $e) {
承知致しました！
なので、、保存するテーブルが違うだけで、ほとんど同じ感じでかけばいいんだなってなるとよいです！！
→わかってはいるんですけど、機能が違う/ファイルが増えると考えすぎてしまって中々指摘されるまで築けないことが多いです。。。
深く考えすぎないで、同じ型！を意識したいと思います。

修正いたしましたのでご確認宜しくお願いします。

2023-10-20 00:02 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-10-20 09:53 UTC, merged