feat:Edit機能をDDD構造にする
yuta10200831/7-2.docker-templete pull request #28
Opened 2023-09-30 12:55 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/2-1758b8c7441944bc8206cebc259a7459

## 作業詳細
Edit機能をDDD構造にする！

2023-10-01 19:07 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-10-01 19:07 UTC, KatsuyaTanaka95 commented on src/public/edit.php
> +$blogRepo = new BlogRepositoryMySQLImpl($pdo);
BlogRepositoryMySQLImplクラス内で 「new PDO」をしましょう！
UserDaoと同じように作成しましょう！

2023-10-01 19:07 UTC, KatsuyaTanaka95 commented on src/public/post/update.php
> +$blogRepo = new BlogRepositoryMySQLImpl($pdo);
BlogRepositoryMySQLImplクラス内で 「new PDO」をしましょう！
UserDaoと同じように作成しましょう！

2023-10-01 19:07 UTC, KatsuyaTanaka95 commented on src/public/post/update.php
> +$blogRepo->update($blog);
ユーザー登録機能の同じように UseCaseを作成しましょう！

2023-10-05 00:08 UTC, yuta10200831 commented on src/public/edit.php
> +$blogRepo = new BlogRepositoryMySQLImpl($pdo);
修正済み

2023-10-05 14:11 UTC, yuta10200831 commented
修正しました！
見づらく大変申し訳ございません。
ご確認宜しくお願い致します。

2023-10-06 05:45 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-10-06 05:45 UTC, KatsuyaTanaka95 commented on src/public/edit.php
> +use App\Infrastructure\Dao\BlogRepositoryMySQLImpl;
「use App\Infrastructure\Dao\BlogRepositoryMySQLImpl;」は、session_start();より上に書きましょう！！

2023-10-06 05:45 UTC, KatsuyaTanaka95 commented on src/public/post/update.php
> +use App\Infrastructure\Dao\BlogRepositoryMySQLImpl;
これらのコードは、session_start();の上に書きましょう！

2023-10-06 05:45 UTC, KatsuyaTanaka95 commented on src/public/post/update.php
> +}
ログイン機能と同じような構成になってなさそうです！
以下のURLのプルリクのコメントを参考にこちらも修正してみてください！（スクショの箇所です！）
https://github.com/yuta10200831/7-2.docker-templete/pull/26
<img width="276" alt="スクリーンショット 2023-10-06 14 41 09" src="https://github.com/yuta10200831/7-2.docker-templete/assets/63081802/4328b071-84c3-4a40-b033-e1721a0485b6">

2023-12-02 09:01 UTC, closed without merging