feat:10月3日　質問用
yuta10200831/7-2.docker-templete pull request #29
Opened 2023-10-03 14:15 UTC by yuta10200831

質問用にプルリクを作らせて頂きました。

(内容)
新規登録処理ができない。

(仮説)
・データの受け渡しが出来ていない
・データの登録処理ができていない

(検証)
・デバッグをして処理が動いているか、データが格納されているかを確認
・再度参考資料を見て流れの確認
・DBの確認
・DB接続ができているかの確認
・一旦立ち止まって思考を紙に書いて整理する

2023-10-07 10:38 UTC, yuta10200831 commented
NULL

2023-12-01 00:35 UTC, yuta10200831 commented
エラーメッセージの件、0を許容する作りにして作理直し解消しました。
UserId周りをひたすらにvar_dumpしまくりましたがこの解決方法しか思いつきませんでした、、

UserId.php
`throw new Exception(self::INVALID_MESSAGE);`の直前でvar＿dumpすると`int(0)`と表示されます。
この値を許容すれば単純にエラーが解消すると思いこの対応をしています。
実際にエラーは解消しました。

しかし、ここでint(0)と出ることが正しいのかどうか頭が混乱しております、、でもDBには正常に保存できている、、

アドバイス頂きたいです、宜しくお願いします！

2023-12-01 03:32 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
今回は、ヒントの共有にさせていただきます！！！
もう少し頑張ってみてください！！！！😊

2023-12-02 07:09 UTC, yuta10200831 commented on src/app/Domain/ValueObject/User/UserId.php
> +     * 0以上かどうかを判定する
signup_completeにて下記コードをコメントアウトすることによってエラーメッセージを消すことができました。
```
    // $lastUserId = $userDao->getPdo()->lastInsertId();
    // $userAgeObject = new UserAge(new UserId($lastUserId), new Age($age));
    // $userAgeDao->create($userAgeObject);
```

signupInteractor.phpにも同じ処理をしているコードがあったのでこのような対応をしています。。

users_ageテーブルに２つデータが登録される
上記を確認する事ができずにいるのですが、、どのようにしたら再現できるのか分からずにいます。
<img width="644" alt="スクリーンショット 2023-12-02 16 08 48" src="https://github.com/yuta10200831/7-2.docker-templete/assets/124555669/6a6f7e03-e178-4205-bf9b-97a26998633e">

2023-12-04 08:29 UTC, KatsuyaTanaka95 approved these changes
signup_completeにもusers_ageテーブルにデータを登録する処理がかいてあったのでエラーしてましたね！！
あっております！！！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

こちらですが、、UserId.phpの値の範囲を「0以上かどうかを判定する」のままで試しましたでしょうか？？
> users_ageテーブルに２つデータが登録される
> 上記を確認する事ができずにいるのですが、、どのようにしたら再現できるのか分からずにいます。
<img width="828" alt="スクリーンショット 2023-12-04 17 27 58" src="https://github.com/yuta10200831/7-2.docker-templete/assets/63081802/8c6363b8-6549-49d4-9099-2b7f219c73b7">

2023-12-04 09:35 UTC, merged