feat:edit機能をDDD構造にする
yuta10200831/7-2.docker-templete pull request #30
Opened 2023-12-07 15:19 UTC by yuta10200831

作業対象
[作業をした教材のURL]
https://www.notion.so/2-1758b8c7441944bc8206cebc259a7459

作業詳細
edit機能をDDD構造にする

2023-12-07 21:30 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-12-07 21:30 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseOutput/UpdateOutput.php
> +    }
引数の$isSuccess ですが、、どんな場合でもtrueなのであれば、消してしまいましょう！
`$isSuccess = true`

2023-12-07 21:30 UTC, KatsuyaTanaka95 commented on src/app/Infrastructure/Dao/UpdateDao.php
> +    private $pdo;
Daoは機能ごとではなく、テーブルごとに作成するようにしましょう！
なので、、blogDaoにブログのデータの更新処理を書きましょう！！
↓↓教材を再度見直しましょう！
www.notion.so/2-1758b8c7441944bc8206cebc259a7459?pvs=4#e63dc2814ff547e59480ae2617775972
<img width="1355" alt="スクリーンショット 2023-12-08 6 17 13" src="https://github.com/yuta10200831/7-2.docker-templete/assets/63081802/458c1793-83c4-4acb-9e4c-6ac65700cf0d">

2023-12-07 21:30 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseInteractor/UpdateInteractor.php
> +        $existingUpdate->setContents($this->input->getContents());
このようにデータをセットし直すのはやめましょう！！
どの時点でどのデータが入っているのか確認しないといけなくなるので、、ややこしいコードになってしまいます！！！

2023-12-07 21:30 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseInteractor/UpdateInteractor.php
> +        $this->updateRepository->update($existingUpdate);
ここの引数には、$this->inputを渡しましょう！

2023-12-07 21:30 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseInteractor/UpdateGetInteractor.php
> +        return new UpdateOutput($update);
UpdateInteractorで使用しているOutputと別のOutputを使用するようにしましょう！

2023-12-07 21:30 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseInteractor/UpdateGetInteractor.php
> +        return new UpdateOutput($update);
UpdateInteractorと別のOutputクラスを使用するようにしましょう！

2023-12-08 07:44 UTC, yuta10200831 commented on src/app/UseCase/UseCaseInteractor/UpdateInteractor.php
> +        $this->updateRepository->update($existingUpdate);
承知致しました！
修正しました。

2023-12-08 07:57 UTC, yuta10200831 commented on src/app/UseCase/UseCaseInteractor/UpdateGetInteractor.php
> +        return new UpdateOutput($update);
承知致しました！
修正いたしました。

2023-12-08 08:06 UTC, yuta10200831 commented
修正いたしました。
改めてご確認宜しくお願いします！

2023-12-10 14:40 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-12-11 13:12 UTC, merged