(完)feat:CommentCreateのテスト
yuta10200831/7-2.docker-templete pull request #39
Opened 2023-12-13 12:10 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/4-5b5f746793774e1091a40ad3c3c8741d

## 作業詳細
UseCaseのCommentCreateテスト
![スクリーンショット 2024-01-06 21 37 10](https://github.com/yuta10200831/7-2.docker-templete/assets/124555669/4aad72ce-496c-4aa2-834c-1a9d1905bd3d)

2024-01-08 22:42 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご確認をお願いいたします！🙆🙋😊🌟💫

2024-01-08 22:42 UTC, KatsuyaTanaka95 commented on src/test/UseCase/CommentCreateTest.php
> +        $_SESSION['user']['id'] = 123;
ここのセッションは、何で使用していますか？？
（布施木さんが書いているってことは、必要な可能性もあると考えたため確認させてください！）
使用していなければ、削除してしまいましょう！！

2024-01-09 15:22 UTC, yuta10200831 commented on src/test/UseCase/CommentCreateTest.php
> +        $_SESSION['user']['id'] = 123;
レビューありがとうございます！
CommentCreateInteractorr.phpのhandler()内でどのユーザーが投稿したか識別するために記載していた為、
テストコードも合わせたほうが良いのではないかと思いこのような記述にしておりました。
しかし、改めて考えるとテストコードではモックを使用している為、この記述は不要だなと田中さんに言われて気づきました。

こちら削除しましたので改めてご確認宜しくお願いします！

2024-01-09 22:44 UTC, KatsuyaTanaka95 approved these changes
ご丁寧に回答いただきありがとうございます。
良い流れで学習が進んでいると思います！！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2024-01-09 23:25 UTC, merged