feat:CommentGetのテスト
yuta10200831/7-2.docker-templete pull request #40
Opened 2023-12-13 14:14 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/4-5b5f746793774e1091a40ad3c3c8741d

## 作業詳細
UseCaseのCommentGetテスト
※エラーが出ている箇所はCommentCreateのテストをした際に出たものです
  エラー解消ができないため後ほど質問しようと思い一旦先に進んでいます。

<img width="1475" alt="スクリーンショット 2023-12-13 23 12 56" src="https://github.com/yuta10200831/7-2.docker-templete/assets/124555669/d4191616-6268-4b76-b446-cdeda2a4b71e">

2023-12-13 21:53 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-12-13 21:53 UTC, KatsuyaTanaka95 commented on src/test/UseCase/CommentCreateTest.php
> +    }
Interfaceを作成してテストをするのが望ましいです！！
見本のコードを読んで真似してみましょう！！
（↓↓この課題で参考にしましょうとしているリポジトリのスクショになります！！！）
<img width="724" alt="スクリーンショット 2023-12-14 6 49 17" src="https://github.com/yuta10200831/7-2.docker-templete/assets/63081802/1e2be076-9f77-4a48-936a-4335709c4138">

2024-01-06 15:29 UTC, yuta10200831 commented on src/test/UseCase/CommentCreateTest.php
> +    }
承知致しました！
Interface用のファイルを作り、implementsを用いてテストする用に修正しました。
ご確認宜しくお願いします！

2024-01-06 15:30 UTC, yuta10200831 commented
修正しましたので改めてご確認宜しくお願いします！
<img width="1350" alt="スクリーンショット 2024-01-07 0 30 30" src="https://github.com/yuta10200831/7-2.docker-templete/assets/124555669/847060ce-274c-46f7-be94-4806562c9067">

2024-01-08 22:45 UTC, KatsuyaTanaka95 approved these changes
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2024-01-09 23:26 UTC, merged