feat:CreatePostのテスト
yuta10200831/7-2.docker-templete pull request #41
Opened 2023-12-13 15:01 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/4-5b5f746793774e1091a40ad3c3c8741d

## 作業詳細
UseCaseのCreatePostテストです
※エラーが出ている箇所はCreatePostのテストをした際に出たものです
  エラー解消ができないため後ほど質問しようと思い一旦先に進んでいます。

2023-12-13 21:57 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-12-13 21:57 UTC, KatsuyaTanaka95 commented on src/test/UseCase/CreatePostTest.php
> +}
Interfaceを作成してテストをするのが望ましいです！！
見本のコードを読んで真似してみましょう！！
（↓↓この課題で参考にしましょうとしているリポジトリのスクショになります！！！）
<img width="724" alt="スクリーンショット 2023-12-14 6 49 17" src="https://github.com/yuta10200831/7-2.docker-templete/assets/63081802/1e2be076-9f77-4a48-936a-4335709c4138">

2024-01-08 06:50 UTC, yuta10200831 commented on src/test/UseCase/CreatePostTest.php
> +}
承知致しました！
Interfaceを用いて修正しましたので改めてご確認宜しくお願いします！

2024-01-08 06:51 UTC, yuta10200831 commented
修正しました！
改めてご確認宜しくお願いします！
<img width="1597" alt="スクリーンショット 2024-01-08 15 51 31" src="https://github.com/yuta10200831/7-2.docker-templete/assets/124555669/4078aee9-6c67-49a4-ad57-5c4a08b0d35f">

2024-01-08 22:47 UTC, KatsuyaTanaka95 approved these changes
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2024-01-09 23:27 UTC, merged